User-based collaborative filtering recommends items by finding users with similar tastes to the target user and then suggesting items liked by those similar users.

In [3]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df = pd.read_csv("feedback.csv")

In [5]:
df.head(1)

   user_id  content_id  like_dislike  rating        feedback_date
0        1        1193             1       5  2020-01-23 22:58:09

In [7]:
df = df[['user_id' , 'content_id', 'rating']]

In [9]:
df.isnull().sum()

user_id       0
content_id    0
rating        0
dtype: int64

In [11]:
# Create User x Movie ratings matrix
ratings_matrix = df.pivot_table(
    index='user_id',
    columns='content_id',
    values='rating'
)

In [17]:
ratings_matrix.head()

content_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
ratings_matrix = ratings_matrix.fillna(0)   # Only for similarity calculation

In [39]:
# Compute cosine similarity
user_similarity = cosine_similarity(ratings_matrix)

# Put into a DataFrame for easy reading
user_similarity_df = pd.DataFrame(
    user_similarity, 
    index=ratings_matrix.index, 
    columns=ratings_matrix.index
)

In [41]:
user_similarity_df.head()

user_id,1,2,3,4,5,6,7,8,9,10,...,6031,6032,6033,6034,6035,6036,6037,6038,6039,6040
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.104503,0.080240,0.139364,0.088323,0.176237,0.064551,0.159835,0.221336,0.233912,...,0.146556,0.080653,0.078037,0.037355,0.119372,0.174214,0.148710,0.000000,0.155652,0.106137
2,0.104503,1.000000,0.136351,0.178245,0.098719,0.082870,0.290659,0.193232,0.190749,0.179796,...,0.102178,0.076037,0.255792,0.000000,0.164121,0.192397,0.191459,0.056510,0.070636,0.138937
3,0.080240,0.136351,1.000000,0.138626,0.041342,0.042642,0.095273,0.057144,0.118453,0.168866,...,0.064910,0.123463,0.144185,0.000000,0.078459,0.128389,0.079817,0.136864,0.091047,0.085269
4,0.139364,0.178245,0.138626,1.000000,0.037579,0.000000,0.111018,0.084471,0.086817,0.094529,...,0.143242,0.064226,0.346296,0.000000,0.057438,0.187024,0.132436,0.031271,0.051513,0.075842
5,0.088323,0.098719,0.041342,0.037579,1.000000,0.028513,0.101302,0.201471,0.211670,0.078053,...,0.060584,0.035464,0.032711,0.033996,0.125063,0.201885,0.118942,0.012002,0.034358,0.229942

In [51]:
target_user = 1000
similar_users = user_similarity_df[target_user].sort_values(ascending=False).drop(target_user).head(5)
print(similar_users)

user_id
2539    0.482567
5842    0.479641
3906    0.471494
1349    0.465062
1188    0.463439
Name: 1000, dtype: float64

In [53]:
# Movies already rated by target user
rated_by_target = ratings_matrix.loc[target_user]
rated_by_target = rated_by_target[rated_by_target > 0].index

# Get ratings of neighbors
neighbors = similar_users.index
neighbor_ratings = ratings_matrix.loc[neighbors]

# Weighted average of neighbor ratings
weighted_scores = (neighbor_ratings.T.dot(similar_users)) / similar_users.sum()

# Remove movies already rated by target user
recommendations = weighted_scores.drop(rated_by_target, errors='ignore')

# Top 10 recommended movies
top_recommendations = recommendations.sort_values(ascending=False).head(10)
print(top_recommendations)

content_id
1196    3.805815
2944    3.617891
1953    1.999624
2028    1.982378
3753    1.965328
1222    1.832389
3654    1.819831
3104    1.813638
3703    1.801530
474     1.769139
dtype: float64

In [29]:
# Read with "::" as separator
df = pd.read_csv("users.dat", sep="::", engine="python", 
                 names=["UserID", "Gender", "Age", "Occupation", "Zipcode"])


print(df.head())

   UserID Gender  Age  Occupation Zipcode
0       1      F    1          10   48067
1       2      M   56          16   70072
2       3      M   25          15   55117
3       4      M   45           7   02460
4       5      M   25          20   55455

In [19]:
df1 = pd.read_csv("ratings.dat", 
                      sep="::", 
                      engine="python", 
                      names=["user_id", "content_id", "rating", "timestamp"])

print(ratings.head())

   user_id  content_id  rating  timestamp
0        1        1193       5  978300760
1        1         661       3  978302109
2        1         914       3  978301968
3        1        3408       4  978300275
4        1        2355       5  978824291

In [27]:
movies = pd.read_csv(
    "movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",   # <-- Fix UnicodeDecodeError
    names=["content_id", "title", "genres"]
)

print(movies.head())

   content_id                               title  \
0           1                    Toy Story (1995)
1           2                      Jumanji (1995)
2           3             Grumpier Old Men (1995)
3           4            Waiting to Exhale (1995)
4           5  Father of the Bride Part II (1995)

                         genres
0   Animation|Children's|Comedy
1  Adventure|Children's|Fantasy
2                Comedy|Romance
3                  Comedy|Drama
4                        Comedy

In [31]:
pip install requests

Requirement already satisfied: requests in c:\users\hemil\anaconda3\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hemil\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hemil\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hemil\anaconda3\lib\site-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hemil\anaconda3\lib\site-packages (from requests) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [45]:
import pandas as pd
import requests
import re
import time

API_KEY = "8f1d1b01ccbc887118a61d69923a7af7"

# Load movies.dat
movies = pd.read_csv(
    "movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["content_id", "title", "genres"]
)

def extract_title_year(title):
    """Extracts movie title and year from 'Title (Year)' format"""
    match = re.match(r"^(.*)\((\d{4})\)$", title.strip())
    if match:
        return match.group(1).strip(), match.group(2)
    return title, None

def get_movie_description(title):
    """Fetch movie description from TMDB API given a title"""
    movie_title, year = extract_title_year(title)
    url = f"https://api.themoviedb.org/3/search/movie"
    params = {"api_key": API_KEY, "query": movie_title}
    if year:
        params["year"] = year

    for attempt in range(3):  # retry 3 times if error
        try:
            response = requests.get(url, params=params, timeout=10)
            if response.status_code == 200:
                data = response.json()
                if data["results"]:
                    return data["results"][0]["overview"]  # description
                return None
            else:
                print(f"⚠️ Failed for {title}: {response.status_code}")
        except requests.exceptions.RequestException as e:
            print(f"⚠️ Error fetching {title}: {e} (attempt {attempt+1})")
            time.sleep(2)
    return None

# Example: Fetch descriptions for first 5 movies only (test)
movies["description"] = movies["title"].head(5).apply(lambda x: get_movie_description(x))

print(movies.head(10))

# Save results to CSV
movies.to_csv("movies_with_descriptions.csv", index=False, encoding="utf-8")

   content_id                               title  \
0           1                    Toy Story (1995)
1           2                      Jumanji (1995)
2           3             Grumpier Old Men (1995)
3           4            Waiting to Exhale (1995)
4           5  Father of the Bride Part II (1995)
5           6                         Heat (1995)
6           7                      Sabrina (1995)
7           8                 Tom and Huck (1995)
8           9                 Sudden Death (1995)
9          10                    GoldenEye (1995)

                         genres  \
0   Animation|Children's|Comedy
1  Adventure|Children's|Fantasy
2                Comedy|Romance
3                  Comedy|Drama
4                        Comedy
5         Action|Crime|Thriller
6                Comedy|Romance
7          Adventure|Children's
8                        Action
9     Action|Adventure|Thriller

                                         description
0  Led by Woody, Andy's toys live happily in his ...
1  When siblings Judy and Peter discover an encha...
2  A family wedding reignites the ancient feud be...
3  Cheated on, mistreated and stepped on, the wom...
4  Just when George Banks has recovered from his ...
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

In [53]:
dfr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   content_id   3883 non-null   int64
 1   title        3883 non-null   object
 2   genres       3883 non-null   object
 3   description  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 121.5+ KB

In [56]:
dfr = pd.read_csv("movies_with_descriptions.csv")
dfr.head()

,content_id,title,genres,description
0,1,Toy Story (1995),Animation|Children's|Comedy,NaN
1,2,Jumanji (1995),Adventure|Children's|Fantasy,NaN
2,3,Grumpier Old Men (1995),Comedy|Romance,NaN
3,4,Waiting to Exhale (1995),Comedy|Drama,NaN
4,5,Father of the Bride Part II (1995),Comedy,NaN

In [59]:
movies.head()

,content_id,title,genres,description
0,1,Toy Story (1995),Animation|Children's|Comedy,None
1,2,Jumanji (1995),Adventure|Children's|Fantasy,None
2,3,Grumpier Old Men (1995),Comedy|Romance,None
3,4,Waiting to Exhale (1995),Comedy|Drama,None
4,5,Father of the Bride Part II (1995),Comedy,None

In [67]:
# Read movies.dat file
movies = pd.read_csv(
    "movies.dat",
    sep="::",
    engine="python",   # because "::" is multi-character separator
    encoding="latin-1",
    names=["content_id", "title", "genres"]
)

# Save to CSV
movies.to_csv("movies.csv", index=False, encoding="utf-8")

print("✅ movies.dat converted to movies.csv")
print(movies.head())

✅ movies.dat converted to movies.csv
   content_id                               title  \
0           1                    Toy Story (1995)
1           2                      Jumanji (1995)
2           3             Grumpier Old Men (1995)
3           4            Waiting to Exhale (1995)
4           5  Father of the Bride Part II (1995)

                         genres
0   Animation|Children's|Comedy
1  Adventure|Children's|Fantasy
2                Comedy|Romance
3                  Comedy|Drama
4                        Comedy

In [71]:
import pandas as pd
import requests
import re
import time

API_KEY = "8f1d1b01ccbc887118a61d69923a7af7"

# Load movies.csv
movies = pd.read_csv("movies.csv")

def clean_title(title):
    """Remove year in parentheses from title"""
    return re.sub(r"\(\d{4}\)", "", title).strip()

def get_movie_description(title):
    """Fetch movie description from TMDb API given a title"""
    url = f"https://api.themoviedb.org/3/search/movie?api_key={API_KEY}&query={title}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            if data["results"]:
                return data["results"][0]["overview"]  # take first match
    except Exception as e:
        print(f"Error for {title}: {e}")
    return None

# Clean titles
movies["clean_title"] = movies["title"].apply(clean_title)

# Fetch descriptions
descriptions = []
for i, title in enumerate(movies["clean_title"]):
    desc = get_movie_description(title)
    descriptions.append(desc)
    print(f"{i+1}/{len(movies)} Processed: {title} -> {desc}")
    time.sleep(0.25)  # avoid API rate limit

movies["description"] = descriptions

# Save to new CSV
movies.to_csv("movies_with_descriptions.csv", index=False, encoding="utf-8")

print("✅ Movies with descriptions saved to movies_with_descriptions.csv")

1/3883 Processed: Toy Story -> Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.
2/3883 Processed: Jumanji -> When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.
3/3883 Processed: Grumpier Old Men -> A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max.
4/3883 Processed: Waiting to Exhale -> Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive "good man" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, Glo and Robin talk it all out, determined to find a better way to breathe.
5/3883 Processed: Father of the Bride Part II -> Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife is expecting too. He was planning on selling their home, but that's a plan that—like George—will have to change with the arrival of both a grandchild and a kid of his own.
6/3883 Processed: Heat -> Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.
7/3883 Processed: Sabrina -> A toy manufacturer and his wife are terrorized by a demon after their orphaned niece tries to call her late mother's spirit.
8/3883 Processed: Tom and Huck -> A mischievous young boy, Tom Sawyer, witnesses a murder by the deadly Injun Joe. Tom becomes friends with Huckleberry Finn, a boy with no future and no family. Tom has to choose between honoring a friendship or honoring an oath because the town alcoholic is accused of the murder. Tom and Huck go through several adventures trying to retrieve evidence.
9/3883 Processed: Sudden Death -> A kid is riding a bike to his home and realising that he’s not alone
10/3883 Processed: GoldenEye -> When a powerful satellite system falls into the hands of Alec Trevelyan, AKA Agent 006, a former ally-turned-enemy, only James Bond can save the world from a dangerous space weapon that -- in one short pulse -- could destroy the earth! As Bond squares off against his former compatriot, he also battles Xenia Onatopp, an assassin who uses pleasure as her ultimate weapon.
11/3883 Processed: American President, The -> Widowed U.S. president Andrew Shepherd, one of the world's most powerful men, can have anything he wants -- and what he covets most is Sydney Ellen Wade, a Washington lobbyist. But Shepherd's attempts at courting her spark wild rumors and decimate his approval ratings.
12/3883 Processed: Dracula: Dead and Loving It -> When a lawyer shows up at the vampire's doorstep, he falls prey to his charms and joins him in his search for fresh blood. Enter Professor Van Helsing, who may be the only one able to vanquish the Count.
13/3883 Processed: Balto -> An outcast half-wolf risks his life to prevent a deadly epidemic from ravaging Nome, Alaska.
14/3883 Processed: Nixon -> A look at President Richard M. Nixon—a man carrying the fate of the world on his shoulders while battling the self-destructive demands from within—spanning his troubled boyhood in California to the shocking Watergate scandal that would end his Presidency.
15/3883 Processed: Cutthroat Island -> Morgan Adams and her slave, William Shaw, are on a quest to recover the three portions of a treasure map. Unfortunately, the final portion is held by her murderous uncle, Dawg. Her crew is skeptical of her leadership abilities, so she must complete her quest before they mutiny against her. This is made yet more difficult by the efforts of the British crown to end her pirate raids.
16/3883 Processed: Casino -> In early-1970s Las Vegas, Sam "Ace" Rothstein gets tapped by his bosses to head the Tangiers Casino. At first, he's a great success in the job, but over the years, problems with his loose-cannon enforcer Nicky Santoro, his ex-hustler wife Ginger, her con-artist ex Lester Diamond and a handful of corrupt politicians put Sam in ever-increasing danger.
17/3883 Processed: Sense and Sensibility -> The Dashwood sisters, sensible Elinor and passionate Marianne, whose chances at marriage seem doomed by their family's sudden loss of fortune.  When Henry Dashwood dies unexpectedly, his estate must pass on by law to his son from his first marriage, John and wife Fanny. But these circumstances leave Mr. Dashwood's current wife, and daughters Elinor, Marianne and Margaret, without a home and with barely enough money to live on. As Elinor and Marianne struggle to find romantic fulfillment in a society obsessed with financial and social status, they must learn to mix sense with sensibility in their dealings with both money and men.
18/3883 Processed: Four Rooms -> It's Ted the Bellhop's first night on the job...and the hotel's very unusual guests are about to place him in some outrageous predicaments. It seems that this evening's room service is serving up one unbelievable happening after another.
19/3883 Processed: Ace Ventura: When Nature Calls -> Summoned from an ashram in Tibet, Ace finds himself on a perilous journey into the jungles of Africa to find Shikaka, the missing sacred animal of the friendly Wachati tribe. He must accomplish this before the wedding of the Wachati's Princess to the prince of the warrior Wachootoos. If Ace fails, the result will be a vicious tribal war.
20/3883 Processed: Money Train -> When a vengeful New York transit cop decides to steal a trainload of subway fares, his foster brother—a fellow cop—tries to protect him.
21/3883 Processed: Get Shorty -> Chili Palmer is a Miami mobster who gets sent to L.A. to collect a bad debt from Harry Zimm, a Hollywood producer who specializes in cheesy horror films. When Chili meets Harry's leading lady, the romantic sparks fly. After pitching his own life story as a movie idea, Chili learns that being a mobster and being a Hollywood producer really aren't all that different.
22/3883 Processed: Copycat -> An agoraphobic psychologist and a female detective must work together to take down a serial killer who copies serial killers from the past.
23/3883 Processed: Assassins -> True crime meets global spy thriller in this gripping account of the assassination of Kim Jong-nam, the half brother of the North Korean leader. The film follows the trial of the two female assassins, probing the question: were the women trained killers or innocent pawns of North Korea?
24/3883 Processed: Powder -> Harassed by classmates who won't accept his shocking appearance, a shy young man known as "Powder" struggles to fit in. But the cruel taunts stop when Powder displays a mysterious power that allows him to do incredible things. This phenomenon changes the lives of all those around him in ways they never could have imagined.
25/3883 Processed: Leaving Las Vegas -> Ben Sanderson, an alcoholic Hollywood screenwriter who lost everything because of his drinking, arrives in Las Vegas to drink himself to death. There, he meets and forms an uneasy friendship and non-interference pact with prostitute Sera.
26/3883 Processed: Othello -> With freshly rechristened characters and brand-new dialogue, this British TV production of Othello is a "rethinking" of Shakespeare's play, albeit still retaining the original's power and potency. The story is set in the London of the near future, a crime-ridden metropolis virtually torn apart by racial hostilities. By order of the Prime Minister, black police officer John Othello (Eamonn Walker) is promoted to Commissioner, a post dearly coveted by Othello's friend, mentor and fellow officer Ben Jago (Christopher Eccleston). Seething with jealousy, Jago contrives to discredit Othello in the eyes of the public, and to destroy John's interracial marriage to the lily-white Dessie (Keeley Hawes). Among those used as unwitting dupes to gain Jago's ends are Othello's trusted lieutenant, Michael Cass (Richard Coyle), scrupulously honest police constable Alan Roderick (Del Synnott), and Jago's own wife, Lulu (Rachael Stirling).
27/3883 Processed: Now and Then -> While moving house, a middle-aged Muslim woman finds a box of old tapes filled with the memories of her husband's previous relationship and becomes increasingly obsessed.
28/3883 Processed: Persuasion -> Anne Elliot, the daughter of a financially troubled aristocratic family, is persuaded to break her engagement to Frederick Wentworth, a young sea captain of meager means. Years later, money troubles force Anne's father to rent out the family estate to Admiral Croft, and Anne is again thrown into company with Frederick -- who is now rich, successful, and perhaps still in love with Anne.
29/3883 Processed: City of Lost Children, The -> A scientist in a surrealist society kidnaps children to steal their dreams, hoping that they slow his aging process.
30/3883 Processed: Shanghai Triad (Yao a yao yao dao waipo qiao) -> None
31/3883 Processed: Dangerous Minds -> Former Marine Louanne Johnson lands a gig teaching in a pilot program for bright but underachieving teens at a notorious inner-city high school. After having a terrible first day, she decides she must throw decorum to the wind. When Johnson returns to the classroom, she does so armed with a no-nonsense attitude informed by her military training and a fearless determination to better the lives of her students -- no matter what the cost.
32/3883 Processed: Twelve Monkeys -> In the year 2035, convict James Cole reluctantly volunteers to be sent back in time to discover the origin of a deadly virus that wiped out nearly all of the earth's population and forced the survivors into underground communities. But when Cole is mistakenly sent to 1990 instead of 1996, he's arrested and locked up in a mental hospital. There he meets psychiatrist Dr. Kathryn Railly and the son of a famous virus expert who may hold the key to the Army of the 12 Monkeys; thought to be responsible for unleashing the killer disease.
33/3883 Processed: Wings of Courage -> In 1930 South America, a small group of French pilots struggle to prove they can offer a reliable airmail service over the Andes. When one of the young pilots crashes on such a flight, he has to try and get back to civilization on foot. Back home, his wife and colleagues start to fear the worst.
34/3883 Processed: Babe -> Babe is a little pig who doesn't quite know his place in the world. With a bunch of odd friends, like Ferdinand the duck who thinks he is a rooster and Fly the dog he calls mum, Babe realises that he has the makings to become the greatest sheep pig of all time, and Farmer Hoggett knows it. With the help of the sheep dogs, Babe learns that a pig can be anything that he wants to be.
35/3883 Processed: Carrington -> Painter Dora Carrington develops an intimate but extremely complex bond with writer Lytton Strachey. Though Lytton is a homosexual, he is enchanted by the mysterious Dora and they begin a lifelong friendship that has strangely romantic undertones. Eventually, Lytton and Dora decide to live together, despite the fact that the latter has fallen in love with military man Ralph Partridge, whom she plans to marry.
36/3883 Processed: Dead Man Walking -> A death row inmate turns for spiritual guidance to a local nun in the days leading up to his scheduled execution for the murders of a young couple.
37/3883 Processed: Across the Sea of Time -> A young Russian boy, Thomas Minton, travels to New York as a passenger on a Russian freighter. Close to Ellis Island he gets off and thus starts his journey to America the same way as all immigrants in former times. Thomas is searching for the family of one of his ancestors, who had emigrated decades ago, but once sent a letter home together with a sample of his new profession: 3D-Photography.
38/3883 Processed: It Takes Two -> Identical 9-year-olds from very different backgrounds: orphaned Amanda and wealthy Alyssa meet at summer camp and decide to switch places -- and play matchmaker between Alyssa's dad, Roger, and the kind social worker who cares for Amanda.
39/3883 Processed: Clueless -> Shallow, rich and socially successful Cher is at the top of her Beverly Hills high school's pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other. Emboldened by her success, she decides to give hopelessly klutzy new student Tai a makeover. When Tai becomes more popular than she is, Cher realizes that her disapproving ex-stepbrother was right about how misguided she was -- and falls for him.
40/3883 Processed: Cry, the Beloved Country -> A South-African preacher goes to search for his wayward son who has committed a crime in the big city.
41/3883 Processed: Richard III -> Richard of Gloucester uses murder and manipulation to claim England's throne.
42/3883 Processed: Dead Presidents -> On the streets they call cash dead presidents. And that's just what a Vietnam veteran is after when he returns home from the war only to find himself drawn into a life of crime. With the aid of his fellow vets he plans the ultimate heist -- a daring robbery of an armored car filled with unmarked U.S. currency!
43/3883 Processed: Restoration -> An aspiring young physician, Robert Merivel found himself in the service of King Charles II and saves the life of someone close to the King. Merivel joins the King's court and lives the high life provided to someone of his position. Merivel is ordered to marry his King's mistress in order to divert the queens suspicions. He is given one order by the king and that is not to fall in love. The situation worsens when Merivel finds himself in love with his new wife. Eventually, the King finds out and relieves Merivel of his position and wealth. His fall from grace leaves Merivel where he first started. And through his travels and reunions with an old friend, he rediscovers his love for true medicine and what it really means to be a physician.
44/3883 Processed: Mortal Kombat -> Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.
45/3883 Processed: To Die For -> Civil war reigns in one of the most dangerous areas of the world for 7 years. The Turkish army enters the region without any allied states. Among the officials in the region, there are also the Special Forces team under the command of Captain Alparslan. Together with Captain Pilot Onur, Tim brings out a big trap against the Turkish army. In order to break the trap, the main test for the team that fights the lives of terrorists against the terrorists in the difficult conditions is to be able to survive without losing their conscience.
46/3883 Processed: How to Make an American Quilt -> Soon-to-be-wed graduate student Finn Dodd develops cold feet when she suspects her fiancé is cheating on her. In order to clear her head, Finn visits her grandmother, Hy, and great aunt, Glady Joe Cleary, in Grasse, Calif. There, Finn learns that Hy and Glady Joe are members of a group of passionate quilters, and over the course of her visit she is regaled with tales of love and life by women who have collected rich experiences and much wisdom.
47/3883 Processed: Seven (Se7en) -> Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Somerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.
48/3883 Processed: Pocahontas -> Pocahontas, daughter of a Native American tribe chief, falls in love with an English soldier as colonists invade 17th century Virginia.
49/3883 Processed: When Night Is Falling -> Camille is a professor at a Protestant college and is in a long-term relationship Martin, a respected minister and fellow professor. When Camille meets Petra, a bold and flamboyant performer in a circus troupe, she is inexplicably drawn. Pursuing Petra, Camille throws her whole conservative life into disarray.
50/3883 Processed: Usual Suspects, The -> Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro harbor – leaving few survivors. Verbal lures his interrogators with an incredible story of the crime lord's almost supernatural prowess.
51/3883 Processed: Guardian Angel -> After the tragic death of his wife, Ray, a veteran security specialist, must protect the daughter of a businessman who embezzled millions from a crime boss in Los Angeles. Uncovering much more than he bargained for, Ray takes matters into his own...
52/3883 Processed: Mighty Aphrodite -> When Lenny and his wife, Amanda, adopt a baby, Lenny realizes that his son is a genius and becomes obsessed with finding the boy's biological mother in hopes that she will be brilliant too. But when he learns that Max's mother is Linda Ash, a kindhearted prostitute and porn star, Lenny is determined to reform her immoral lifestyle. A Greek chorus chimes in to relate the plot to Greek mythology in this quirky comedy.
53/3883 Processed: Lamerica -> Fiore, an Italian conman, arrives in post Communist Albania with Gino, his young apprentice, to set up a shoe factory that will never open. The con requires a native Albanian, so they designate Spiro, an impoverished and confused former political prisoner as chairman of the board. When Fiore returns to Italy to get government funds for the project, Spiro unexpectedly disappears and Gino sets out on a journey to find him. The search leads him to discover Spiro's tragic personal history and witness Albanian poverty firsthand.
54/3883 Processed: Big Green, The -> In a depressed Texas town, British foreign exchange teacher Anna attempts to inject some life into her hopeless kids by introducing them to soccer. They're terrible at first, but Anna and her football-hero assistant whip them into shape. As they work overtime, the pair help kids build their self-esteem and also get involved in solving family squabbles.
55/3883 Processed: Georgia -> Sadie looks up to her older sister Georgia, a successful folk singer. Unfortunately it is this very obsession — coupled with her self-destructive tendencies and rampant drug abuse — that keeps her spiraling down the drain.
56/3883 Processed: Kids of the Round Table -> Set in modern times, Alex finds King Arthur's sword Excalibur and must prove himself worthy of it.

In [ ]:
import pandas as pd
import requests
import re
import time

API_KEY = "8f1d1b01ccbc887118a61d69923a7af7"

# Load movies.csv
movies = pd.read_csv("movies.csv")

def clean_title(title):
    """Remove year in parentheses from title"""
    return re.sub(r"\(\d{4}\)", "", title).strip()

def get_movie_info(title):
    """Fetch movie description + director from TMDb"""
    search_url = f"https://api.themoviedb.org/3/search/movie?api_key={API_KEY}&query={title}"
    try:
        search_resp = requests.get(search_url)
        if search_resp.status_code == 200:
            data = search_resp.json()
            if data["results"]:
                movie_id = data["results"][0]["id"]
                description = data["results"][0].get("overview")

                # now fetch credits for director
                credits_url = f"https://api.themoviedb.org/3/movie/{movie_id}/credits?api_key={API_KEY}"
                credits_resp = requests.get(credits_url)
                director = None
                if credits_resp.status_code == 200:
                    crew = credits_resp.json().get("crew", [])
                    for member in crew:
                        if member["job"] == "Director":
                            director = member["name"]
                            break

                return description, director
    except Exception as e:
        print(f"Error for {title}: {e}")
    return None, None

# Clean titles
movies["clean_title"] = movies["title"].apply(clean_title)

# Fetch descriptions + directors
descriptions = []
directors = []
for i, title in enumerate(movies["clean_title"]):
    desc, director = get_movie_info(title)
    descriptions.append(desc)
    directors.append(director)
    print(f"{i+1}/{len(movies)} Processed: {title} -> Director: {director}")
    time.sleep(0.25)  # stay under TMDb rate limits

movies["description"] = descriptions
movies["director"] = directors

# Save new CSV
movies.to_csv("movies_with_desc_directors.csv", index=False, encoding="utf-8")

print("✅ Movies with descriptions + directors saved to movies_with_desc_directors.csv")

1/3883 Processed: Toy Story -> Director: John Lasseter
2/3883 Processed: Jumanji -> Director: Joe Johnston
3/3883 Processed: Grumpier Old Men -> Director: Howard Deutch
4/3883 Processed: Waiting to Exhale -> Director: Forest Whitaker
5/3883 Processed: Father of the Bride Part II -> Director: Charles Shyer
6/3883 Processed: Heat -> Director: Michael Mann
7/3883 Processed: Sabrina -> Director: Rocky Soraya
8/3883 Processed: Tom and Huck -> Director: Peter Hewitt
9/3883 Processed: Sudden Death -> Director: Harley Longstaff
10/3883 Processed: GoldenEye -> Director: Martin Campbell
11/3883 Processed: American President, The -> Director: Rob Reiner
12/3883 Processed: Dracula: Dead and Loving It -> Director: Mel Brooks
13/3883 Processed: Balto -> Director: Simon Wells
14/3883 Processed: Nixon -> Director: Oliver Stone
15/3883 Processed: Cutthroat Island -> Director: Renny Harlin
16/3883 Processed: Casino -> Director: Martin Scorsese
17/3883 Processed: Sense and Sensibility -> Director: Ang Lee
18/3883 Processed: Four Rooms -> Director: Allison Anders
19/3883 Processed: Ace Ventura: When Nature Calls -> Director: Steve Oedekerk
20/3883 Processed: Money Train -> Director: Joseph Ruben
21/3883 Processed: Get Shorty -> Director: Barry Sonnenfeld
22/3883 Processed: Copycat -> Director: Jon Amiel
23/3883 Processed: Assassins -> Director: Ryan White
24/3883 Processed: Powder -> Director: Victor Salva
25/3883 Processed: Leaving Las Vegas -> Director: Mike Figgis
26/3883 Processed: Othello -> Director: Geoffrey Sax
27/3883 Processed: Now and Then -> Director: Harris Alvi
28/3883 Processed: Persuasion -> Director: Roger Michell
29/3883 Processed: City of Lost Children, The -> Director: Jean-Pierre Jeunet
30/3883 Processed: Shanghai Triad (Yao a yao yao dao waipo qiao) -> Director: None
31/3883 Processed: Dangerous Minds -> Director: John N. Smith
32/3883 Processed: Twelve Monkeys -> Director: Terry Gilliam
33/3883 Processed: Wings of Courage -> Director: Jean-Jacques Annaud
34/3883 Processed: Babe -> Director: Chris Noonan
35/3883 Processed: Carrington -> Director: Christopher Hampton
36/3883 Processed: Dead Man Walking -> Director: Tim Robbins
37/3883 Processed: Across the Sea of Time -> Director: Stephen Low
38/3883 Processed: It Takes Two -> Director: Andy Tennant
39/3883 Processed: Clueless -> Director: Amy Heckerling
40/3883 Processed: Cry, the Beloved Country -> Director: Darrell James Roodt
41/3883 Processed: Richard III -> Director: Raúl Ruiz
42/3883 Processed: Dead Presidents -> Director: Albert Hughes
43/3883 Processed: Restoration -> Director: Michael Hoffman
44/3883 Processed: Mortal Kombat -> Director: Simon McQuoid
45/3883 Processed: To Die For -> Director: Çağatay Tosun
46/3883 Processed: How to Make an American Quilt -> Director: Jocelyn Moorhouse
47/3883 Processed: Seven (Se7en) -> Director: David Fincher
48/3883 Processed: Pocahontas -> Director: Mike Gabriel
49/3883 Processed: When Night Is Falling -> Director: Patricia Rozema
50/3883 Processed: Usual Suspects, The -> Director: Bryan Singer
51/3883 Processed: Guardian Angel -> Director: Vahik Pirhamzei
52/3883 Processed: Mighty Aphrodite -> Director: Woody Allen
53/3883 Processed: Lamerica -> Director: Gianni Amelio
54/3883 Processed: Big Green, The -> Director: Holly Goldberg Sloan
55/3883 Processed: Georgia -> Director: Ulu Grosbard
56/3883 Processed: Kids of the Round Table -> Director: Robert Tinnell
57/3883 Processed: Home for the Holidays -> Director: Gary Harvey
58/3883 Processed: Postino, Il (The Postman) -> Director: Michael Radford
59/3883 Processed: Confessional, The (Le Confessionnal) -> Director: Robert Lepage
60/3883 Processed: Indian in the Cupboard, The -> Director: Frank Oz
61/3883 Processed: Eye for an Eye -> Director: Paco Plaza
62/3883 Processed: Mr. Holland's Opus -> Director: Stephen Herek
63/3883 Processed: Don't Be a Menace to South Central While Drinking Your Juice in the Hood -> Director: Paris Barclay
64/3883 Processed: Two if by Sea -> Director: Bill Bennett
65/3883 Processed: Bio-Dome -> Director: Jason Bloom
66/3883 Processed: Lawnmower Man 2: Beyond Cyberspace -> Director: Farhad Mann
67/3883 Processed: Two Bits -> Director: James Foley
68/3883 Processed: French Twist (Gazon maudit) -> Director: Josiane Balasko
69/3883 Processed: Friday -> Director: F. Gary Gray
70/3883 Processed: From Dusk Till Dawn -> Director: Robert Rodriguez
71/3883 Processed: Fair Game -> Director: Andrew Sipes
72/3883 Processed: Kicking and Screaming -> Director: Noah Baumbach
73/3883 Processed: Misérables, Les -> Director: Glenn Jordan
74/3883 Processed: Bed of Roses -> Director: Michael Goldenberg
75/3883 Processed: Big Bully -> Director: Steve Miner
76/3883 Processed: Screamers -> Director: Carla Garapedian
77/3883 Processed: Nico Icon -> Director: Susanne Ofteringer
78/3883 Processed: Crossing Guard, The -> Director: Jérôme Savary
79/3883 Processed: Juror, The -> Director: Georges Lautner
80/3883 Processed: White Balloon, The (Badkonake Sefid ) -> Director: Jafar Panahi
81/3883 Processed: Things to Do in Denver when You're Dead -> Director: Gary Fleder
82/3883 Processed: Antonia's Line (Antonia) -> Director: Marleen Gorris
83/3883 Processed: Once Upon a Time... When We Were Colored -> Director: Tim Reid
84/3883 Processed: Last Summer in the Hamptons -> Director: Henry Jaglom
85/3883 Processed: Angels and Insects -> Director: Philip Haas
86/3883 Processed: White Squall -> Director: Ridley Scott
87/3883 Processed: Dunston Checks In -> Director: Ken Kwapis
88/3883 Processed: Black Sheep -> Director: Ed Perkins
89/3883 Processed: Nick of Time -> Director: John Badham
90/3883 Processed: Journey of August King, The -> Director: John Duigan
91/3883 Processed: Mary Reilly -> Director: Stephen Frears
92/3883 Processed: Vampire in Brooklyn -> Director: Wes Craven
93/3883 Processed: Beautiful Girls -> Director: Ted Demme
94/3883 Processed: Broken Arrow -> Director: Peter Kuran
95/3883 Processed: In the Bleak Midwinter -> Director: Kenneth Branagh
96/3883 Processed: Hate (Haine, La) -> Director: Alessandro Santini
97/3883 Processed: Shopping -> Director: Paul W. S. Anderson
98/3883 Processed: Heidi Fleiss: Hollywood Madam -> Director: Nick Broomfield
99/3883 Processed: City Hall -> Director: Harold Becker
100/3883 Processed: Bottle Rocket -> Director: Charlie Webb
101/3883 Processed: Mr. Wrong -> Director: Nick Castle
102/3883 Processed: Unforgettable -> Director: Eric Williams
103/3883 Processed: Happy Gilmore -> Director: Dennis Dugan
104/3883 Processed: Bridges of Madison County, The -> Director: Clint Eastwood
105/3883 Processed: Nobody Loves Me (Keiner liebt mich) -> Director: Doris Dörrie
106/3883 Processed: Muppet Treasure Island -> Director: David Gumpel
107/3883 Processed: Catwalk -> Director: Abbott Meader
108/3883 Processed: Headless Body in Topless Bar -> Director: James Bruce
109/3883 Processed: Braveheart -> Director: Mel Gibson
110/3883 Processed: Taxi Driver -> Director: Martin Scorsese
111/3883 Processed: Rumble in the Bronx -> Director: Stanley Tong Gwai-Lai
112/3883 Processed: Before and After -> Director: Kim Friedman
113/3883 Processed: Margaret's Museum -> Director: Mort Ransen
114/3883 Processed: Happiness Is in the Field -> Director: Étienne Chatiliez
115/3883 Processed: Anne Frank Remembered -> Director: Jon Blair
116/3883 Processed: Young Poisoner's Handbook, The -> Director: Benjamin Ross
117/3883 Processed: If Lucy Fell -> Director: Eric Schaeffer
118/3883 Processed: Steal Big, Steal Little -> Director: Andrew Davis
119/3883 Processed: Race the Sun -> Director: Charles T. Kanganis
120/3883 Processed: Boys of St. Vincent, The -> Director: John N. Smith
121/3883 Processed: Boomerang -> Director: François Favrat
122/3883 Processed: Chungking Express -> Director: Wong Kar-wai
123/3883 Processed: Star Maker, The (Uomo delle stelle, L') -> Director: Giuseppe Tornatore
124/3883 Processed: Flirting With Disaster -> Director: David O. Russell
125/3883 Processed: NeverEnding Story III, The -> Director: Peter MacDonald
126/3883 Processed: Silence of the Palace, The (Saimt el Qusur) -> Director: None
127/3883 Processed: Jupiter's Wife -> Director: Michel Negroponte
128/3883 Processed: Pie in the Sky -> Director: Ralph Steiner
129/3883 Processed: Angela -> Director: Boris Sagal
130/3883 Processed: Frankie Starlight -> Director: Michael Lindsay-Hogg
131/3883 Processed: Jade -> Director: James Bamford
132/3883 Processed: Nueba Yol -> Director: Ángel Muñiz
133/3883 Processed: Sonic Outlaws -> Director: Craig Baldwin
134/3883 Processed: Down Periscope -> Director: David S. Ward
135/3883 Processed: From the Journals of Jean Seberg -> Director: Mark Rappaport
136/3883 Processed: Man of the Year -> Director: José Henrique Fonseca
137/3883 Processed: Neon Bible, The -> Director: Terence Davies
138/3883 Processed: Target -> Director: Raditya Dika
139/3883 Processed: Up Close and Personal -> Director: Bertrand Loyer
140/3883 Processed: Birdcage, The -> Director: Mike Nichols
141/3883 Processed: Shadows (Cienie) -> Director: Jerzy Kaszubowski
142/3883 Processed: Gospa -> Director: Peter Bizjak
143/3883 Processed: Brothers McMullen, The -> Director: Edward Burns
144/3883 Processed: Bad Boys -> Director: Michael Bay
145/3883 Processed: Amazing Panda Adventure, The -> Director: Christopher Cain
146/3883 Processed: Basketball Diaries, The -> Director: Scott Kalvert
147/3883 Processed: Awfully Big Adventure, An -> Director: Mike Newell
148/3883 Processed: Amateur -> Director: Hal Hartley
149/3883 Processed: Apollo 13 -> Director: Ron Howard
150/3883 Processed: Rob Roy -> Director: Geoff Collins
151/3883 Processed: Addiction, The -> Director: Ri Yoon
152/3883 Processed: Batman Forever -> Director: Joel Schumacher
153/3883 Processed: Belle de jour -> Director: Luis Buñuel
154/3883 Processed: Beyond Rangoon -> Director: John Boorman
155/3883 Processed: Blue in the Face -> Director: Wayne Wang
156/3883 Processed: Canadian Bacon -> Director: Michael Moore
157/3883 Processed: Casper -> Director: Brad Silberling
158/3883 Processed: Clockers -> Director: Spike Lee
159/3883 Processed: Congo -> Director: Frank Marshall
160/3883 Processed: Crimson Tide -> Director: Tony Scott
161/3883 Processed: Crumb -> Director: Terry Zwigoff
162/3883 Processed: Desperado -> Director: Robert Rodriguez
163/3883 Processed: Devil in a Blue Dress -> Director: Carl Franklin
164/3883 Processed: Die Hard: With a Vengeance -> Director: John McTiernan
165/3883 Processed: Doom Generation, The -> Director: Gregg Araki
166/3883 Processed: Feast of July -> Director: Christopher Menaul
167/3883 Processed: First Knight -> Director: Jerry Zucker
168/3883 Processed: Free Willy 2: The Adventure Home -> Director: Dwight H. Little
169/3883 Processed: Hackers -> Director: Iain Softley
170/3883 Processed: Jeffrey -> Director: Thomas Affolter
171/3883 Processed: Johnny Mnemonic -> Director: Robert Longo
172/3883 Processed: Judge Dredd -> Director: Luis Junquera
173/3883 Processed: Jury Duty -> Director: John Fortenberry
174/3883 Processed: Kids -> Director: Larry Clark
175/3883 Processed: Living in Oblivion -> Director: Tom DiCillo
176/3883 Processed: Lord of Illusions -> Director: Clive Barker
177/3883 Processed: Love & Human Remains -> Director: Li Han-Hsiang
178/3883 Processed: Mad Love -> Director: Vicente Aranda
179/3883 Processed: Mallrats -> Director: Kevin Smith
180/3883 Processed: Mighty Morphin Power Rangers: The Movie -> Director: Bryan Spicer
181/3883 Processed: Moonlight and Valentino -> Director: David Anspaugh
182/3883 Processed: Mute Witness -> Director: Anthony Waller
183/3883 Processed: Nadja -> Director: Michael Almereyda
184/3883 Processed: Net, The -> Director: Agustí Vila
185/3883 Processed: Nine Months -> Director: Chris Columbus
186/3883 Processed: Party Girl -> Director: Nicholas Ray
187/3883 Processed: Prophecy, The -> Director: Kim Byung-woo
188/3883 Processed: Reckless -> Director: James Foley
189/3883 Processed: Safe -> Director: Alex Kaplan
190/3883 Processed: Scarlet Letter, The -> Director: Byun Hyuk
191/3883 Processed: Show, The -> Director: Kim Eun-kyung
192/3883 Processed: Showgirls -> Director: Paul Verhoeven
193/3883 Processed: Smoke -> Director: Wayne Wang
194/3883 Processed: Something to Talk About -> Director: Lasse Hallström
195/3883 Processed: Species -> Director: Roger Donaldson
196/3883 Processed: Stars Fell on Henrietta, The -> Director: James Keach
197/3883 Processed: Strange Days -> Director: Kathryn Bigelow
198/3883 Processed: Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les) -> Director: Marie Genin
199/3883 Processed: Tie That Binds, The -> Director: Wesley Strick
200/3883 Processed: Three Wishes -> Director: Martha Coolidge
201/3883 Processed: Total Eclipse -> Director: Agnieszka Holland
202/3883 Processed: To Wong Foo, Thanks for Everything! Julie Newmar -> Director: Beeban Kidron
203/3883 Processed: Under Siege 2: Dark Territory -> Director: Geoff Murphy
204/3883 Processed: Unstrung Heroes -> Director: Diane Keaton
205/3883 Processed: Unzipped -> Director: Jenna Miller
206/3883 Processed: Walk in the Clouds, A -> Director: Alfonso Arau
207/3883 Processed: Waterworld -> Director: Kevin Reynolds
208/3883 Processed: White Man's Burden -> Director: Desmond Nakano
209/3883 Processed: Wild Bill -> Director: Dexter Fletcher
210/3883 Processed: Browning Version, The -> Director: Mike Figgis
211/3883 Processed: Bushwhacked -> Director: Greg Beeman
212/3883 Processed: Burnt By the Sun (Utomlyonnye solntsem) -> Director: Nikita Mikhalkov
213/3883 Processed: Before the Rain (Pred dozhdot) -> Director: Milcho Manchevski
214/3883 Processed: Before Sunrise -> Director: Richard Linklater
215/3883 Processed: Billy Madison -> Director: Tamra Davis
216/3883 Processed: Babysitter, The -> Director: Brian Skiba
217/3883 Processed: Boys on the Side -> Director: Herbert Ross
218/3883 Processed: Cure, The -> Director: None
219/3883 Processed: Castle Freak -> Director: Tate Steinsiek
220/3883 Processed: Circle of Friends -> Director: Pat O'Connor
221/3883 Processed: Clerks -> Director: Kevin Smith
222/3883 Processed: Don Juan DeMarco -> Director: Jeremy Leven
223/3883 Processed: Disclosure -> Director: Sam Feder
224/3883 Processed: Dream Man -> Director: René Bonnière
225/3883 Processed: Drop Zone -> Director: John Badham
226/3883 Processed: Destiny Turns on the Radio -> Director: Jack Baran
227/3883 Processed: Death and the Maiden -> Director: Dieter Berner
228/3883 Processed: Dolores Claiborne -> Director: Taylor Hackford
229/3883 Processed: Dumb & Dumber -> Director: Blackie Ko
230/3883 Processed: Eat Drink Man Woman -> Director: Ang Lee
231/3883 Processed: Exotica -> Director: Atom Egoyan
232/3883 Processed: Exit to Eden -> Director: Garry Marshall
233/3883 Processed: Ed Wood -> Director: Tim Burton
234/3883 Processed: French Kiss -> Director: Lawrence Kasdan
235/3883 Processed: Forget Paris -> Director: Billy Crystal
236/3883 Processed: Far From Home: The Adventures of Yellow Dog -> Director: Phillip Borsos
237/3883 Processed: Goofy Movie, A -> Director: Douglas McCarthy
238/3883 Processed: Hideaway -> Director: Brett Leonard
239/3883 Processed: Fluke -> Director: Carlo Carlei
240/3883 Processed: Farinelli: il castrato -> Director: Gérard Corbiau
241/3883 Processed: Gordy -> Director: Mark Lewis
242/3883 Processed: Gumby: The Movie -> Director: Art Clokey
243/3883 Processed: Glass Shield, The -> Director: Charles Burnett
244/3883 Processed: Hoop Dreams -> Director: Steve James
245/3883 Processed: Heavenly Creatures -> Director: Peter Jackson
246/3883 Processed: Houseguest -> Director: Randall Miller
247/3883 Processed: Immortal Beloved -> Director: Bernard Rose
248/3883 Processed: Heavyweights -> Director: Steven Brill
249/3883 Processed: Hunted, The -> Director: Chris Huo
250/3883 Processed: I.Q. -> Director: Fred Schepisi
251/3883 Processed: Interview with the Vampire -> Director: Neil Jordan
252/3883 Processed: Jefferson in Paris -> Director: James Ivory
253/3883 Processed: Jerky Boys, The -> Director: James Melkonian
254/3883 Processed: Junior -> Director: Ivan Reitman
255/3883 Processed: Just Cause -> Director: Arne Glimcher
256/3883 Processed: Kid in King Arthur's Court, A -> Director: Michael Gottlieb
257/3883 Processed: Kiss of Death -> Director: Christian Sesma
258/3883 Processed: Star Wars: Episode IV - A New Hope -> Director: George Lucas
259/3883 Processed: Little Women -> Director: Greta Gerwig
260/3883 Processed: Little Princess, A -> Director: Alfonso Cuarón
261/3883 Processed: Ladybird Ladybird -> Director: Nello Pepe
262/3883 Processed: Enfer, L' -> Director: Alain Payet
263/3883 Processed: Like Water for Chocolate (Como agua para chocolate) -> Director: Ross MacGibbon
264/3883 Processed: Legends of the Fall -> Director: Edward Zwick
265/3883 Processed: Major Payne -> Director: Nick Castle
266/3883 Processed: Little Odessa -> Director: James Gray
267/3883 Processed: My Crazy Life (Mi vida loca) -> Director: Allison Anders
268/3883 Processed: Love Affair -> Director: Kim Jung-hwan
269/3883 Processed: Losing Isaiah -> Director: Stephen Gyllenhaal
270/3883 Processed: Madness of King George, The -> Director: Nicholas Hytner
271/3883 Processed: Mary Shelley's Frankenstein -> Director: Kenneth Branagh
272/3883 Processed: Man of the House -> Director: Stephen Herek
273/3883 Processed: Mixed Nuts -> Director: Mel Brown
274/3883 Processed: Milk Money -> Director: Richard Benjamin
275/3883 Processed: Miracle on 34th Street -> Director: William Corrigan
276/3883 Processed: Miami Rhapsody -> Director: David Frankel
277/3883 Processed: My Family -> Director: Gregory Nava
278/3883 Processed: Murder in the First -> Director: Marc Rocco
279/3883 Processed: Nobody's Fool -> Director: Robert Benton
280/3883 Processed: Nell -> Director: Michael Apted
281/3883 Processed: New Jersey Drive -> Director: Nick Gomez
282/3883 Processed: New York Cop -> Director: Berta Muñiz
283/3883 Processed: Beyond Bedlam -> Director: Vadim Jean
284/3883 Processed: Nemesis 2: Nebula -> Director: Albert Pyun
285/3883 Processed: Nina Takes a Lover -> Director: Alan Jacobs
286/3883 Processed: Natural Born Killers -> Director: Oliver Stone
287/3883 Processed: Only You -> Director: Norman Jewison
288/3883 Processed: Once Were Warriors -> Director: Lee Tamahori
289/3883 Processed: Poison Ivy II -> Director: Anne Goursaud
290/3883 Processed: Outbreak -> Director: Jeff Wolfe
291/3883 Processed: Professional, The (a.k.a. Leon: The Professional) -> Director: None
292/3883 Processed: Perez Family, The -> Director: Gilberto Martínez Solares
293/3883 Processed: Pyromaniac's Love Story, A -> Director: Joshua Brand
294/3883 Processed: Pulp Fiction -> Director: Quentin Tarantino
295/3883 Processed: Panther -> Director: Mario Van Peebles
296/3883 Processed: Pushing Hands -> Director: Ang Lee
297/3883 Processed: Priest -> Director: Scott Stewart
298/3883 Processed: Quiz Show -> Director: Robert Redford
299/3883 Processed: Picture Bride -> Director: Kayo Hatta
300/3883 Processed: Queen Margot (La Reine Margot) -> Director: Camille de Morlhon
301/3883 Processed: Quick and the Dead, The -> Director: Sam Raimi
302/3883 Processed: Roommates -> Director: None
303/3883 Processed: Ready to Wear (Pret-A-Porter) -> Director: Robert Altman
304/3883 Processed: Three Colors: Red -> Director: Krzysztof Kieślowski
305/3883 Processed: Three Colors: Blue -> Director: Krzysztof Kieślowski
306/3883 Processed: Three Colors: White -> Director: Krzysztof Kieślowski
307/3883 Processed: Red Firecracker, Green Firecracker -> Director: He Ping
308/3883 Processed: Rent-a-Kid -> Director: Fred Gerber
309/3883 Processed: Relative Fear -> Director: George Mihalka
310/3883 Processed: Stuart Saves His Family -> Director: Harold Ramis
311/3883 Processed: Swan Princess, The -> Director: Richard Rich
312/3883 Processed: Secret of Roan Inish, The -> Director: John Sayles
313/3883 Processed: Specialist, The -> Director: Luigi Zampa

In [7]:
import pandas as pd
import requests
import re
import time
import os

API_KEY = "8f1d1b01ccbc887118a61d69923a7af7"

# Load CSV (if enriched file exists, resume from there)
if os.path.exists("movies_enriched.csv"):
    movies = pd.read_csv("movies_enriched.csv")
    print("✅ Resuming from movies_enriched.csv")
else:
    movies = pd.read_csv("movies.csv")

# --- Step 1: Split title + year ---
def split_title_year(title):
    match = re.match(r"^(.*)\((\d{4})\)$", title.strip())
    if match:
        return match.group(1).strip(), int(match.group(2))
    return title, None

if "title_without_year" not in movies.columns or "year" not in movies.columns:
    movies[["title_without_year", "year"]] = movies["title"].apply(
        lambda x: pd.Series(split_title_year(x))
    )

# --- Step 2: Safe GET with retries ---
def safe_get(url, retries=5, delay=2):
    for attempt in range(retries):
        try:
            resp = requests.get(url, timeout=15)
            if resp.status_code == 200:
                return resp
            elif resp.status_code == 429:  # Rate limit
                wait_time = int(resp.headers.get("Retry-After", 10))
                print(f"⚠️ Rate limit hit! Waiting {wait_time} seconds...")
                time.sleep(wait_time)
            else:
                print(f"⚠️ Unexpected status {resp.status_code} for {url}")
        except requests.exceptions.RequestException as e:
            print(f"⚠️ Attempt {attempt+1} failed: {e}")
            time.sleep(delay * (attempt + 1))  # exponential backoff
    return None

# --- Step 3: Fetch description + director + cast ---
def get_movie_info(title, year=None, retries=3):
    for attempt in range(retries):
        desc, director, cast = None, None, None

        # Search movie
        search_url = f"https://api.themoviedb.org/3/search/movie?api_key={API_KEY}&query={title}"
        if year:
            search_url += f"&year={year}"

        search_resp = safe_get(search_url)
        if not search_resp:
            print(f"❌ Search failed for {title}, retrying...")
            time.sleep(2 * (attempt + 1))
            continue

        data = search_resp.json()
        if not data["results"]:
            return None, None, None

        movie_id = data["results"][0]["id"]
        desc = data["results"][0].get("overview")

        # Get credits
        credits_url = f"https://api.themoviedb.org/3/movie/{movie_id}/credits?api_key={API_KEY}"
        credits_resp = safe_get(credits_url)
        if credits_resp:
            credits = credits_resp.json()
            crew = credits.get("crew", [])
            cast_list = credits.get("cast", [])

            # Directors
            directors = [m["name"] for m in crew if m.get("job") == "Director"]
            director = ", ".join(directors) if directors else None

            # Top 5 cast
            cast = ", ".join([c["name"] for c in cast_list[:5]]) if cast_list else None

        return desc, director, cast

    # If all retries failed
    print(f"❌ Giving up on {title}")
    return None, None, None

# --- Step 4: Add empty columns if missing ---
for col in ["description", "director", "cast"]:
    if col not in movies.columns:
        movies[col] = None

# --- Step 5: Process all movies ---
for i, row in movies.iterrows():
    # Skip if already filled
    if pd.notna(row["description"]) and pd.notna(row["director"]) and pd.notna(row["cast"]):
        continue  

    desc, director, cast = get_movie_info(row["title_without_year"], row["year"])
    movies.at[i, "description"] = desc
    movies.at[i, "director"] = director
    movies.at[i, "cast"] = cast

    print(f"{i+1}/{len(movies)} ✅ {row['title']} -> Director: {director}")

    # Save progress every 100 movies
    if (i + 1) % 100 == 0:
        movies.to_csv("movies_enriched.csv", index=False, encoding="utf-8")
        print("💾 Progress saved at", i+1)

    time.sleep(1.5)  # respect TMDb rate limits

# --- Step 6: Final save ---
movies.to_csv("movies_enriched.csv", index=False, encoding="utf-8")
print("🎉 All movies enriched and saved to movies_enriched.csv")

1/3883 ✅ Toy Story (1995) -> Director: John Lasseter
2/3883 ✅ Jumanji (1995) -> Director: Joe Johnston
3/3883 ✅ Grumpier Old Men (1995) -> Director: Howard Deutch
4/3883 ✅ Waiting to Exhale (1995) -> Director: Forest Whitaker
5/3883 ✅ Father of the Bride Part II (1995) -> Director: Charles Shyer
6/3883 ✅ Heat (1995) -> Director: Michael Mann
7/3883 ✅ Sabrina (1995) -> Director: Sydney Pollack
8/3883 ✅ Tom and Huck (1995) -> Director: Peter Hewitt
9/3883 ✅ Sudden Death (1995) -> Director: Peter Hyams
10/3883 ✅ GoldenEye (1995) -> Director: Martin Campbell
11/3883 ✅ American President, The (1995) -> Director: Rob Reiner
12/3883 ✅ Dracula: Dead and Loving It (1995) -> Director: Mel Brooks
13/3883 ✅ Balto (1995) -> Director: Simon Wells
14/3883 ✅ Nixon (1995) -> Director: Oliver Stone
15/3883 ✅ Cutthroat Island (1995) -> Director: Renny Harlin
16/3883 ✅ Casino (1995) -> Director: Martin Scorsese
17/3883 ✅ Sense and Sensibility (1995) -> Director: Ang Lee
18/3883 ✅ Four Rooms (1995) -> Director: Allison Anders, Alexandre Rockwell, Quentin Tarantino, Robert Rodriguez
19/3883 ✅ Ace Ventura: When Nature Calls (1995) -> Director: Steve Oedekerk
20/3883 ✅ Money Train (1995) -> Director: Joseph Ruben
21/3883 ✅ Get Shorty (1995) -> Director: Barry Sonnenfeld
22/3883 ✅ Copycat (1995) -> Director: Jon Amiel
23/3883 ✅ Assassins (1995) -> Director: Richard Donner
24/3883 ✅ Powder (1995) -> Director: Victor Salva
25/3883 ✅ Leaving Las Vegas (1995) -> Director: Mike Figgis
26/3883 ✅ Othello (1995) -> Director: Oliver Parker
27/3883 ✅ Now and Then (1995) -> Director: Lesli Linka Glatter
28/3883 ✅ Persuasion (1995) -> Director: Roger Michell
29/3883 ✅ City of Lost Children, The (1995) -> Director: Jean-Pierre Jeunet, Marc Caro
30/3883 ✅ Shanghai Triad (Yao a yao yao dao waipo qiao) (1995) -> Director: None
31/3883 ✅ Dangerous Minds (1995) -> Director: John N. Smith
32/3883 ✅ Twelve Monkeys (1995) -> Director: Terry Gilliam
33/3883 ✅ Wings of Courage (1995) -> Director: Jean-Jacques Annaud
34/3883 ✅ Babe (1995) -> Director: Chris Noonan
35/3883 ✅ Carrington (1995) -> Director: Christopher Hampton
36/3883 ✅ Dead Man Walking (1995) -> Director: Tim Robbins
37/3883 ✅ Across the Sea of Time (1995) -> Director: Stephen Low
38/3883 ✅ It Takes Two (1995) -> Director: Andy Tennant
39/3883 ✅ Clueless (1995) -> Director: Amy Heckerling
40/3883 ✅ Cry, the Beloved Country (1995) -> Director: Darrell James Roodt
41/3883 ✅ Richard III (1995) -> Director: Richard Loncraine
42/3883 ✅ Dead Presidents (1995) -> Director: Albert Hughes, Allen Hughes
43/3883 ✅ Restoration (1995) -> Director: Michael Hoffman
44/3883 ✅ Mortal Kombat (1995) -> Director: Paul W. S. Anderson
45/3883 ✅ To Die For (1995) -> Director: Gus Van Sant
46/3883 ✅ How to Make an American Quilt (1995) -> Director: Jocelyn Moorhouse
47/3883 ✅ Seven (Se7en) (1995) -> Director: David Fincher
48/3883 ✅ Pocahontas (1995) -> Director: Mike Gabriel, Eric Goldberg
49/3883 ✅ When Night Is Falling (1995) -> Director: Patricia Rozema
50/3883 ✅ Usual Suspects, The (1995) -> Director: Bryan Singer
51/3883 ✅ Guardian Angel (1994) -> Director: Richard W. Munchkin
52/3883 ✅ Mighty Aphrodite (1995) -> Director: Woody Allen
53/3883 ✅ Lamerica (1994) -> Director: Gianni Amelio
54/3883 ✅ Big Green, The (1995) -> Director: Holly Goldberg Sloan
55/3883 ✅ Georgia (1995) -> Director: Ulu Grosbard
56/3883 ✅ Kids of the Round Table (1995) -> Director: Robert Tinnell
57/3883 ✅ Home for the Holidays (1995) -> Director: Jodie Foster
58/3883 ✅ Postino, Il (The Postman) (1994) -> Director: Michael Radford
59/3883 ✅ Confessional, The (Le Confessionnal) (1995) -> Director: Robert Lepage
60/3883 ✅ Indian in the Cupboard, The (1995) -> Director: Frank Oz
61/3883 ✅ Eye for an Eye (1996) -> Director: John Schlesinger
62/3883 ✅ Mr. Holland's Opus (1995) -> Director: Stephen Herek
63/3883 ✅ Don't Be a Menace to South Central While Drinking Your Juice in the Hood (1996) -> Director: Paris Barclay
64/3883 ✅ Two if by Sea (1996) -> Director: Bill Bennett
65/3883 ✅ Bio-Dome (1996) -> Director: Jason Bloom
66/3883 ✅ Lawnmower Man 2: Beyond Cyberspace (1996) -> Director: Farhad Mann
67/3883 ✅ Two Bits (1995) -> Director: James Foley
68/3883 ✅ French Twist (Gazon maudit) (1995) -> Director: Josiane Balasko
69/3883 ✅ Friday (1995) -> Director: F. Gary Gray
70/3883 ✅ From Dusk Till Dawn (1996) -> Director: Robert Rodriguez
71/3883 ✅ Fair Game (1995) -> Director: Andrew Sipes
72/3883 ✅ Kicking and Screaming (1995) -> Director: Noah Baumbach
73/3883 ✅ Misérables, Les (1995) -> Director: Claude Lelouch
74/3883 ✅ Bed of Roses (1996) -> Director: Michael Goldenberg
75/3883 ✅ Big Bully (1996) -> Director: Steve Miner
76/3883 ✅ Screamers (1995) -> Director: Christian Duguay
77/3883 ✅ Nico Icon (1995) -> Director: Susanne Ofteringer
78/3883 ✅ Crossing Guard, The (1995) -> Director: Sean Penn
79/3883 ✅ Juror, The (1996) -> Director: Brian Gibson
80/3883 ✅ White Balloon, The (Badkonake Sefid ) (1995) -> Director: Jafar Panahi
81/3883 ✅ Things to Do in Denver when You're Dead (1995) -> Director: Gary Fleder
82/3883 ✅ Antonia's Line (Antonia) (1995) -> Director: Marleen Gorris
83/3883 ✅ Once Upon a Time... When We Were Colored (1995) -> Director: Tim Reid
84/3883 ✅ Last Summer in the Hamptons (1995) -> Director: Henry Jaglom
85/3883 ✅ Angels and Insects (1995) -> Director: Philip Haas
86/3883 ✅ White Squall (1996) -> Director: Ridley Scott
87/3883 ✅ Dunston Checks In (1996) -> Director: Ken Kwapis
88/3883 ✅ Black Sheep (1996) -> Director: Penelope Spheeris
89/3883 ✅ Nick of Time (1995) -> Director: John Badham
90/3883 ✅ Journey of August King, The (1995) -> Director: John Duigan
91/3883 ✅ Mary Reilly (1996) -> Director: Stephen Frears
92/3883 ✅ Vampire in Brooklyn (1995) -> Director: Wes Craven
93/3883 ✅ Beautiful Girls (1996) -> Director: Ted Demme
94/3883 ✅ Broken Arrow (1996) -> Director: John Woo
95/3883 ✅ In the Bleak Midwinter (1995) -> Director: Kenneth Branagh
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
96/3883 ✅ Hate (Haine, La) (1995) -> Director: Mathieu Kassovitz
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
97/3883 ✅ Shopping (1994) -> Director: Paul W. S. Anderson
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
98/3883 ✅ Heidi Fleiss: Hollywood Madam (1995) -> Director: Nick Broomfield
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
99/3883 ✅ City Hall (1996) -> Director: Harold Becker
100/3883 ✅ Bottle Rocket (1996) -> Director: Wes Anderson
💾 Progress saved at 100
101/3883 ✅ Mr. Wrong (1996) -> Director: Nick Castle
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
102/3883 ✅ Unforgettable (1996) -> Director: John Dahl
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
103/3883 ✅ Happy Gilmore (1996) -> Director: Dennis Dugan
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
104/3883 ✅ Bridges of Madison County, The (1995) -> Director: Clint Eastwood
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 4 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 5 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
❌ Search failed for Nobody Loves Me (Keiner liebt mich), retrying...
105/3883 ✅ Nobody Loves Me (Keiner liebt mich) (1994) -> Director: Doris Dörrie
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
106/3883 ✅ Muppet Treasure Island (1996) -> Director: David Gumpel
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 4 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
107/3883 ✅ Catwalk (1995) -> Director: Robert Leacock
108/3883 ✅ Headless Body in Topless Bar (1995) -> Director: James Bruce
109/3883 ✅ Braveheart (1995) -> Director: Mel Gibson
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
110/3883 ✅ Taxi Driver (1976) -> Director: Martin Scorsese
111/3883 ✅ Rumble in the Bronx (1995) -> Director: Stanley Tong Gwai-Lai
112/3883 ✅ Before and After (1996) -> Director: Barbet Schroeder
113/3883 ✅ Margaret's Museum (1995) -> Director: Mort Ransen
114/3883 ✅ Happiness Is in the Field (1995) -> Director: Étienne Chatiliez
115/3883 ✅ Anne Frank Remembered (1995) -> Director: Jon Blair
116/3883 ✅ Young Poisoner's Handbook, The (1995) -> Director: Benjamin Ross
117/3883 ✅ If Lucy Fell (1996) -> Director: Eric Schaeffer
118/3883 ✅ Steal Big, Steal Little (1995) -> Director: Andrew Davis
119/3883 ✅ Race the Sun (1996) -> Director: Charles T. Kanganis
120/3883 ✅ Boys of St. Vincent, The (1993) -> Director: None
121/3883 ✅ Boomerang (1992) -> Director: Reginald Hudlin
122/3883 ✅ Chungking Express (1994) -> Director: Wong Kar-wai
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 4 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 5 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
123/3883 ✅ Star Maker, The (Uomo delle stelle, L') (1995) -> Director: None
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 4 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 5 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
❌ Search failed for Flirting With Disaster, retrying...
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
124/3883 ✅ Flirting With Disaster (1996) -> Director: David O. Russell
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
125/3883 ✅ NeverEnding Story III, The (1994) -> Director: Peter MacDonald
126/3883 ✅ Silence of the Palace, The (Saimt el Qusur) (1994) -> Director: None
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
127/3883 ✅ Jupiter's Wife (1994) -> Director: None
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
128/3883 ✅ Pie in the Sky (1995) -> Director: Bryan Gordon
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
129/3883 ✅ Angela (1995) -> Director: Rebecca Miller
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
130/3883 ✅ Frankie Starlight (1995) -> Director: Michael Lindsay-Hogg
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
131/3883 ✅ Jade (1995) -> Director: William Friedkin
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
132/3883 ✅ Nueba Yol (1995) -> Director: Ángel Muñiz
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
133/3883 ✅ Sonic Outlaws (1995) -> Director: Craig Baldwin
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
134/3883 ✅ Down Periscope (1996) -> Director: David S. Ward
135/3883 ✅ From the Journals of Jean Seberg (1995) -> Director: Mark Rappaport
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
136/3883 ✅ Man of the Year (1995) -> Director: Dirk Shafer
137/3883 ✅ Neon Bible, The (1995) -> Director: Terence Davies
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
138/3883 ✅ Target (1995) -> Director: Sandip Ray
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
139/3883 ✅ Up Close and Personal (1996) -> Director: Jon Avnet
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
140/3883 ✅ Birdcage, The (1996) -> Director: Mike Nichols
141/3883 ✅ Shadows (Cienie) (1988) -> Director: Jerzy Kaszubowski
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
142/3883 ✅ Gospa (1995) -> Director: Jakov Sedlar
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
143/3883 ✅ Brothers McMullen, The (1995) -> Director: Edward Burns
144/3883 ✅ Bad Boys (1995) -> Director: Michael Bay
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 2 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⚠️ Attempt 3 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
145/3883 ✅ Amazing Panda Adventure, The (1995) -> Director: Christopher Cain
146/3883 ✅ Basketball Diaries, The (1995) -> Director: Scott Kalvert
147/3883 ✅ Awfully Big Adventure, An (1995) -> Director: Mike Newell
⚠️ Attempt 1 failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))